# Generated by Django 5.2 on 2025-04-07 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameAdmin',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_admin_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
