# Generated by Django 5.2 on 2025-04-09 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
        ('gameAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamer',
            name='games',
            field=models.ManyToManyField(blank=True, null=True, related_name='gamers_games', to='gameAdmin.game'),
        ),
        migrations.AddField(
            model_name='gamer',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamer_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
