# Generated by Django 5.2 on 2025-04-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_gamer_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamer',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
