# Generated by Django 5.2 on 2025-04-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_gamer'),
        ('gamer', '0003_alter_game_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamer',
            name='games',
            field=models.ManyToManyField(blank=True, null=True, related_name='gamers_games', to='gamer.game'),
        ),
    ]
