# Generated by Django 5.2 on 2025-04-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_gamer_nickname'),
        ('gameAdmin', '0003_alter_game_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamer',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='gamers', to='gameAdmin.game'),
        ),
    ]
