# Generated by Django 5.2 on 2025-04-07 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_gameadmin'),
        ('gamer', '0002_alter_genre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_created_by', to='auth_app.gameadmin'),
        ),
    ]
