# Generated by Django 5.2 on 2025-04-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamer', '0003_alter_game_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
