# Generated by Django 5.2 on 2025-04-10 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameAdmin', '0003_alter_game_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_event', to='gameAdmin.game'),
        ),
    ]
